### PR TITLE
Fix diff for dexterity behaviors (Plone 5.0)

### PR DESCRIPTION
**Pull request by cedricmessiant**
See https://github.com/plone/Products.CMFDiffTool/pull/7

### CODE REVIEW

**Comment by jensens** [comment]
Test are running here: http://jenkins.plone.org/job/pull-request-5.0/142/

**Comment by jensens** [comment]
Some test failures...

**Comment by cedricmessiant** [comment]
Yes, I saw that. I'll fix those tomorrow or maybe next week. Thanks

**Comment by cedricmessiant** [comment]
Tests should be ok now

**Comment by jensens** [comment]
thanks! lets Jenkins decide ;)  http://jenkins.plone.org/job/pull-request-5.0/195/

**Pull request merged**
